// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SieGraSieMa.Models;

namespace SieGraSieMa.Migrations
{
    [DbContext(typeof(SieGraSieMaContext))]
    [Migration("20220524190739_MediaAlbumsChange_OtherLittleChanges")]
    partial class MediaAlbumsChange_OtherLittleChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "b7065742-4e3f-4c9b-843a-ed4fa6af8752",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "2c1cffa2-20e9-40ba-a277-8cde4000c177",
                            Name = "Emp",
                            NormalizedName = "Emp"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "8306e7d0-3e16-4645-9971-e157102a7a43",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Name")
                        .HasMaxLength(85)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime")
                        .HasColumnName("create_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<int?>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TournamentId" }, "album_tournament");

                    b.ToTable("album");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TournamentId" }, "contest_tournament");

                    b.ToTable("contest");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Contestant", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int")
                        .HasColumnName("contest_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Points")
                        .HasColumnType("int")
                        .HasColumnName("points");

                    b.HasKey("ContestId", "UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "contestants_user");

                    b.ToTable("contestants");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Ladder")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ladder");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("name");

                    b.Property<int>("Phase")
                        .HasColumnType("int")
                        .HasColumnName("phase");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TournamentId" }, "group_tournament");

                    b.HasIndex(new[] { "Name", "TournamentId" }, "name_in_tournament")
                        .IsUnique();

                    b.ToTable("group");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("action");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime")
                        .HasColumnName("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "logs_user");

                    b.ToTable("logs");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Match", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.Property<int>("Phase")
                        .HasColumnType("int")
                        .HasColumnName("phase");

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("match_id");

                    b.Property<int?>("TeamAwayId")
                        .HasColumnType("int")
                        .HasColumnName("team_away_id");

                    b.Property<int?>("TeamAwayScore")
                        .HasColumnType("int")
                        .HasColumnName("team_away_score");

                    b.Property<int?>("TeamHomeId")
                        .HasColumnType("int")
                        .HasColumnName("team_home_id");

                    b.Property<int?>("TeamHomeScore")
                        .HasColumnType("int")
                        .HasColumnName("team_home_score");

                    b.HasKey("TournamentId", "Phase", "MatchId")
                        .HasName("PRIMARY");

                    b.HasIndex("TeamAwayId");

                    b.HasIndex(new[] { "TeamHomeId", "TeamAwayId" }, "meet")
                        .IsUnique();

                    b.ToTable("match");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Medium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("media");
                });

            modelBuilder.Entity("SieGraSieMa.Models.MediumInAlbum", b =>
                {
                    b.Property<int>("AlbumId")
                        .HasColumnType("int")
                        .HasColumnName("album_id");

                    b.Property<int>("MediumId")
                        .HasColumnType("int")
                        .HasColumnName("medium_id");

                    b.HasKey("AlbumId", "MediumId")
                        .HasName("PRIMARY");

                    b.HasIndex("MediumId");

                    b.ToTable("medium_in_album");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Newsletter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "newsletter_user");

                    b.ToTable("newsletter");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SieGraSieMa.Models.Player", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TeamId", "UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "player_user");

                    b.ToTable("player");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            UserId = 3
                        },
                        new
                        {
                            TeamId = 1,
                            UserId = 4
                        },
                        new
                        {
                            TeamId = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("SieGraSieMa.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("created");

                    b.Property<string>("CreatedByIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("createdByIp");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime")
                        .HasColumnName("expires");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text")
                        .HasColumnName("replacedByToken");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime")
                        .HasColumnName("revoked");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("revokedByIp");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "Id" }, "Id")
                        .IsUnique();

                    b.ToTable("refresh_token");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("CaptainId")
                        .HasColumnType("int")
                        .HasColumnName("captain_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("char(5)")
                        .HasColumnName("code")
                        .IsFixedLength(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CaptainId" }, "captain");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.ToTable("team");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaptainId = 3,
                            Code = "ABCDE",
                            Name = "Bogowie"
                        },
                        new
                        {
                            Id = 2,
                            CaptainId = 3,
                            Code = "EDCBA",
                            Name = "Demony"
                        });
                });

            modelBuilder.Entity("SieGraSieMa.Models.TeamInGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "GroupId" }, "team_in_group_group");

                    b.HasIndex(new[] { "TeamId" }, "team_in_group_team");

                    b.ToTable("team_in_group");
                });

            modelBuilder.Entity("SieGraSieMa.Models.TeamInTournament", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("team_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("tournament_id");

                    b.Property<bool>("Paid")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("paid");

                    b.HasKey("TeamId", "TournamentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TournamentId" }, "team_in_tournament_tournament");

                    b.ToTable("team_in_tournament");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime")
                        .HasColumnName("start_date");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.ToTable("tournament");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Zbożowa -1",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Turniej testowy numer 1",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SieGraSieMa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("surname");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d0aa1aa-f1b8-458e-a987-da14a951bb32",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Adm",
                            NormalizedEmail = "admin@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEA2+q9cCUOoeFByry88+GaK3uBsDCOoN330ZckqTD/c7QjUzMYDZdZ97rxHwd0xeWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9205fdd-3861-40a5-b226-5499f0d70c0f",
                            Surname = "In",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e98156ba-1418-44a9-b223-9a4f66a6b9c5",
                            Email = "pracownik@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Prac",
                            NormalizedEmail = "pracownik@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEICS1oIPyJXxADMyDF7CF0L0U1fCICB0YDD+21PcoYhIBtvXy6IHhboHNo77x4NCrQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c893db7-705d-4401-bf1d-6e3e9a29dbce",
                            Surname = "Ownik",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81cc1420-7000-431a-bc52-46d2a3758a5b",
                            Email = "kapitan@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Kap",
                            NormalizedEmail = "kapitan@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAENuUNUcdZcYuT+yYHBetlJ/oGSUCCxPrpIRDdHVOmA5feQt1ysz9aVzr0/5mxL12vg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9b122e83-044f-44d4-b525-11dcbc3e30b0",
                            Surname = "Itan",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1a58a9db-f458-4a23-9acc-3a29c5e75b5e",
                            Email = "gracz@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Gr",
                            NormalizedEmail = "gracz@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEL2LXFSobVB/zFW11oDDzeHrne4wRbCiV3BeryKq2RVB3mU445qY8Q3tf203qoIgzw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "350f3fcf-9412-4f78-a94b-0bd66bfdd364",
                            Surname = "acz",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SieGraSieMa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SieGraSieMa.Models.Album", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Tournament", "Tournament")
                        .WithMany("Albums")
                        .HasForeignKey("TournamentId")
                        .HasConstraintName("album_tournament");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Contest", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Tournament", "Tournament")
                        .WithMany("Contests")
                        .HasForeignKey("TournamentId")
                        .HasConstraintName("contest_tournament")
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Contestant", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Contest", "Contest")
                        .WithMany("Contestants")
                        .HasForeignKey("ContestId")
                        .HasConstraintName("contestants_contest")
                        .IsRequired();

                    b.HasOne("SieGraSieMa.Models.User", "User")
                        .WithMany("Contestants")
                        .HasForeignKey("UserId")
                        .HasConstraintName("contestants_user")
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Group", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Tournament", "Tournament")
                        .WithMany("Groups")
                        .HasForeignKey("TournamentId")
                        .HasConstraintName("group_tournament")
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Log", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("logs_user")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Match", b =>
                {
                    b.HasOne("SieGraSieMa.Models.TeamInGroup", "TeamAway")
                        .WithMany("MatchTeamAways")
                        .HasForeignKey("TeamAwayId")
                        .HasConstraintName("match_away");

                    b.HasOne("SieGraSieMa.Models.TeamInGroup", "TeamHome")
                        .WithMany("MatchTeamHomes")
                        .HasForeignKey("TeamHomeId")
                        .HasConstraintName("match_home");

                    b.HasOne("SieGraSieMa.Models.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .HasConstraintName("tournament")
                        .IsRequired();

                    b.Navigation("TeamAway");

                    b.Navigation("TeamHome");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SieGraSieMa.Models.MediumInAlbum", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Album", "Album")
                        .WithMany("MediumInAlbums")
                        .HasForeignKey("AlbumId")
                        .HasConstraintName("medium_in_album_album")
                        .IsRequired();

                    b.HasOne("SieGraSieMa.Models.Medium", "Medium")
                        .WithMany("MediumInAlbums")
                        .HasForeignKey("MediumId")
                        .HasConstraintName("medium_in_album_media")
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Medium");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Newsletter", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", "User")
                        .WithMany("Newsletters")
                        .HasForeignKey("UserId")
                        .HasConstraintName("newsletter_user")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Player", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("player_team")
                        .IsRequired();

                    b.HasOne("SieGraSieMa.Models.User", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .HasConstraintName("player_user")
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SieGraSieMa.Models.RefreshToken", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("refresh_token_user")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Team", b =>
                {
                    b.HasOne("SieGraSieMa.Models.User", "Captain")
                        .WithMany("Teams")
                        .HasForeignKey("CaptainId")
                        .HasConstraintName("captain")
                        .IsRequired();

                    b.Navigation("Captain");
                });

            modelBuilder.Entity("SieGraSieMa.Models.TeamInGroup", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Group", "Group")
                        .WithMany("TeamInGroups")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("team_in_group_group")
                        .IsRequired();

                    b.HasOne("SieGraSieMa.Models.Team", "Team")
                        .WithMany("TeamInGroups")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("team_in_group_team");

                    b.Navigation("Group");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SieGraSieMa.Models.TeamInTournament", b =>
                {
                    b.HasOne("SieGraSieMa.Models.Team", "Team")
                        .WithMany("TeamInTournaments")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("team_in_tournament_team")
                        .IsRequired();

                    b.HasOne("SieGraSieMa.Models.Tournament", "Tournament")
                        .WithMany("TeamInTournaments")
                        .HasForeignKey("TournamentId")
                        .HasConstraintName("team_in_tournament_tournament")
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Album", b =>
                {
                    b.Navigation("MediumInAlbums");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Contest", b =>
                {
                    b.Navigation("Contestants");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Group", b =>
                {
                    b.Navigation("TeamInGroups");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Medium", b =>
                {
                    b.Navigation("MediumInAlbums");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Team", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("TeamInGroups");

                    b.Navigation("TeamInTournaments");
                });

            modelBuilder.Entity("SieGraSieMa.Models.TeamInGroup", b =>
                {
                    b.Navigation("MatchTeamAways");

                    b.Navigation("MatchTeamHomes");
                });

            modelBuilder.Entity("SieGraSieMa.Models.Tournament", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("Contests");

                    b.Navigation("Groups");

                    b.Navigation("Matches");

                    b.Navigation("TeamInTournaments");
                });

            modelBuilder.Entity("SieGraSieMa.Models.User", b =>
                {
                    b.Navigation("Contestants");

                    b.Navigation("Logs");

                    b.Navigation("Newsletters");

                    b.Navigation("Players");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
