services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    ports:
      - "3306:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: shor+Amber60
      MYSQL_DATABASE: default_schema
    volumes:
      - mysqldata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./siegrasiema.sql:/docker-entrypoint-initdb.d/siegrasiema.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
        - 8183:80
volumes:
  mysqldata: