CREATE DATABASE SieGraSieMa CHARACTER SET utf8mb4 COLLATE utf8mb4_polish_ci;
CREATE USER 'apiuser'@'%' IDENTIFIED WITH caching_sha2_password BY 'di2zyPlant39';
GRANT USAGE ON *.* TO 'apiuser'@'%';
ALTER USER 'apiuser'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `SieGraSieMa`.* TO 'apiuser'@'%';